---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Definicion Red Test"


Parameters:
 VPCId:
  Type: String
 Subnet1PubId:
  Type: String
 Subnet2PubId:
  Type: String

Resources: 
 TestIGW:
  Type: "AWS::EC2::InternetGateway"
  Properties:
   Tags:
    - Key: "Name"
      Value: "TestIGW"
 TestIGWAttach:
  Type: "AWS::EC2::VPCGatewayAttachment"
  Properties:
   InternetGatewayId: !Ref TestIGW
   VpcId: !Ref VPCId
 TestRouteTable:
  Type: "AWS::EC2::RouteTable"
  Properties:
   VpcId: !Ref VPCId
   Tags:
    - Key: "Name"
      Value: "TestRouteTable"
 DefaultRoute:
  Type: "AWS::EC2::Route"
  DependsOn: "TestIGWAttach"
  Properties:
   DestinationCidrBlock: "0.0.0.0/0"
   GatewayId: !Ref TestIGW
   RouteTableId: !Ref TestRouteTable
 RouteTableAssociationPub1:
  Type: "AWS::EC2::SubnetRouteTableAssociation"
  Properties:
    SubnetId: !Ref Subnet1PubId
    RouteTableId: !Ref TestRouteTable
 RouteTableAssociationPub2:
  Type: "AWS::EC2::SubnetRouteTableAssociation"
  Properties:
    SubnetId: !Ref Subnet2PubId
    RouteTableId: !Ref TestRouteTable
