---

AWSTemplateFormatVersion: "2010-09-09"
Description: "Entorno Frontales"

Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-eu-west-1.amazonaws.com/cf180308/CFTest_Stack_Network.yml"
      Parameters:
        CIDRvpc: "10.100.0.0/16"
        CIDRpub1: "10.100.10.0/24"
        CIDRpub2: "10.100.20.0/24"
        CIDRpriv1: "10.100.110.0/24"
        CIDRpriv2: "10.100.120.0/24"
  VPCInfra:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-eu-west-1.amazonaws.com/cf180308/CFTest_Stack_NetInfra.yml"
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCIdentifier
        Subnet1PubId: !GetAtt VPCStack.Outputs.SubnetPub1Identifier
        Subnet2PubId: !GetAtt VPCStack.Outputs.SubnetPub2Identifier

Outputs:
  VPCId: 
    Value: !GetAtt VPCStack.Outputs.VPCIdentifier